basic.forever(function () {
    music.playMelody("G A B A G A B A ", 120)
    music.playMelody("C D E D - - - - ", 120)
    music.playMelody("D - D - D - - - ", 120)
    basic.showString("the doorbell")
    music.playMelody("B B G G B B G G ", 120)
    music.playMelody("B - B - A - B - ", 120)
    music.playMelody("G G - - G G - - ", 120)
    music.playMelody("F F D D F F D D ", 120)
    music.playMelody("E - E - D - E - ", 120)
    music.playMelody("F F - F F - - - ", 120)
    basic.showString("jingle bells")
    music.playMelody("A - A - A - - - ", 120)
    music.playMelody("A - A - A - - - ", 120)
    music.playMelody("A F C5 B A - - - ", 120)
    music.playMelody("G - G - G - - - ", 120)
    music.playMelody("G - G A - A - - ", 120)
    music.playMelody("A A - A B - B A ", 120)
    music.playMelody("B - E E E E - - ", 120)
    music.playMelody("- - - - - - - - ", 120)
})
